Repository ilfm/toongather, pull requests merged in 2025-02, with the labels that each got.

#6 [회원] 회원 머지
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/toongather/toongather/domain/keyword/domain/Keyword.java
  src/main/java/com/toongather/toongather/domain/member/dto/MemberDto.java
  src/main/java/com/toongather/toongather/domain/review/api/ReviewController.java
  src/main/java/com/toongather/toongather/domain/review/domain/Review.java
  src/main/java/com/toongather/toongather/domain/review/domain/ReviewKeyword.java
  src/main/java/com/toongather/toongather/domain/review/dto/CreateReviewRequest.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewDetailDto.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewDto.java
  src/main/java/com/toongather/toongather/domain/review/repository/ReviewRepository.java
  src/main/java/com/toongather/toongather/domain/review/service/ReviewService.java
  src/main/java/com/toongather/toongather/domain/webtoon/WebtoonDto.java
  src/main/java/com/toongather/toongather/domain/webtoon/api/WebtoonController.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/WebtoonGenreKeyword.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/WebtoonStatus.java
  src/main/java/com/toongather/toongather/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/com/toongather/toongather/domain/webtoon/service/PlatformService.java
  src/main/java/com/toongather/toongather/domain/webtoon/service/WebtoonService.java
  src/main/java/com/toongather/toongather/global/common/BaseEntity.java
  src/main/java/com/toongather/toongather/global/common/api/FileController.java
  src/test/java/com/toongather/toongather/ReviewRepositoryTest.java
  src/test/java/com/toongather/toongather/WebtoonRepositoryTest.java
Labels: refactor

#16 [리뷰] 정렬 조건에 따른 전체 리뷰 조회 기능
  src/main/java/com/toongather/toongather/SeqGenerator.java
  src/main/java/com/toongather/toongather/domain/keyword/domain/Keyword.java
  src/main/java/com/toongather/toongather/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/toongather/toongather/domain/review/api/ReviewController.java
  src/main/java/com/toongather/toongather/domain/review/domain/Review.java
  src/main/java/com/toongather/toongather/domain/review/domain/ReviewKeyword.java
  src/main/java/com/toongather/toongather/domain/review/domain/ReviewRecord.java
  src/main/java/com/toongather/toongather/domain/review/domain/ReviewSortType.java
  src/main/java/com/toongather/toongather/domain/review/dto/CreateMyKeywordRequest.java
  src/main/java/com/toongather/toongather/domain/review/dto/CreateReviewRecordRequest.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewDto.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewKeywordDto.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewRecordDto.java
  src/main/java/com/toongather/toongather/domain/review/dto/ReviewSearchDto.java
  src/main/java/com/toongather/toongather/domain/review/dto/UpdateReviewRequest.java
  src/main/java/com/toongather/toongather/domain/review/repository/ReviewJpaRepository.java
  src/main/java/com/toongather/toongather/domain/review/repository/ReviewKeywordRepository.java
  src/main/java/com/toongather/toongather/domain/review/repository/ReviewRecordRepository.java
  src/main/java/com/toongather/toongather/domain/review/repository/ReviewRepository.java
  src/main/java/com/toongather/toongather/domain/review/service/ReviewService.java
  src/main/java/com/toongather/toongather/domain/webtoon/WebtoonDto.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/Webtoon.java
  src/main/java/com/toongather/toongather/global/common/BaseEntity.java
  src/main/java/com/toongather/toongather/global/common/util/file/FileStore.java
  src/main/java/com/toongather/toongather/global/common/util/file/UploadFile.java
  src/test/java/com/toongather/toongather/ReviewRepositoryTest.java
  src/test/java/com/toongather/toongather/WebtoonRepositoryTest.java
  src/test/java/com/toongather/toongather/domain/review/repository/ReviewJpaRepositoryTest.java
Labels: feature

#12 [회원] config 분리 및 gradle 수정
  build.gradle
  src/main/java/com/toongather/toongather/ToongatherApplication.java
  src/main/java/com/toongather/toongather/global/config/JpaAuditingConfig.java
Labels: refactor

#7 [회원] 회원 리팩토링 및 머지
  build.gradle
  src/main/java/com/toongather/toongather/domain/member/api/AuthApi.java
  src/main/java/com/toongather/toongather/domain/member/api/MemberApi.java
  src/main/java/com/toongather/toongather/domain/member/domain/Member.java
  src/main/java/com/toongather/toongather/domain/member/domain/MemberType.java
  src/main/java/com/toongather/toongather/domain/member/dto/JoinFormDTO.java
  src/main/java/com/toongather/toongather/domain/member/dto/MemberDTO.java
  src/main/java/com/toongather/toongather/domain/member/dto/MemberDto.java
  src/main/java/com/toongather/toongather/domain/member/repository/MemberRepository.java
  src/main/java/com/toongather/toongather/domain/member/service/AuthService.java
  src/main/java/com/toongather/toongather/domain/member/service/EmailService.java
  src/main/java/com/toongather/toongather/domain/member/service/MemberService.java
  src/main/java/com/toongather/toongather/global/common/ResponseDTO.java
  src/main/java/com/toongather/toongather/global/config/SecurityConfig.java
  src/main/java/com/toongather/toongather/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/toongather/toongather/global/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/toongather/toongather/global/security/oauth2/UserOAuth2Service.java
  src/main/resources/application.yaml
  src/main/resources/templates/resetpwd.html
  src/main/resources/templates/tempcode.html
  src/test/java/com/toongather/toongather/ToongatherApplicationTests.java
  src/test/java/com/toongather/toongather/domain/member/service/MemberServiceTest.java
Labels: refactor

#20 [웹툰] 등록, 수정, 삭제 기능 추가
  src/main/java/com/toongather/toongather/domain/webtoon/api/WebtoonController.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/GenreKeyword.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/Webtoon.java
  src/main/java/com/toongather/toongather/domain/webtoon/domain/WebtoonGenreKeyword.java
  src/main/java/com/toongather/toongather/domain/webtoon/dto/WebtoonCreateResponse.java
  src/main/java/com/toongather/toongather/domain/webtoon/dto/WebtoonRequest.java
  src/main/java/com/toongather/toongather/domain/webtoon/repository/GenreKeywordRepository.java
  src/main/java/com/toongather/toongather/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/com/toongather/toongather/domain/webtoon/service/WebtoonService.java
  src/test/java/com/toongather/toongather/WebtoonRepositoryTest.java
Labels: feature

#23 [공통] 공통응답 및 공통에러 처리
  src/main/java/com/toongather/toongather/domain/member/api/MemberApi.java
  src/main/java/com/toongather/toongather/global/common/ApiResponse.java
  src/main/java/com/toongather/toongather/global/common/ResponseDTO.java
  src/main/java/com/toongather/toongather/global/common/advice/ApiExceptionAdvice.java
  src/main/java/com/toongather/toongather/global/common/advice/ResponseAdvice.java
  src/main/java/com/toongather/toongather/global/common/error/CommonError.java
  src/main/java/com/toongather/toongather/global/common/error/CommonErrorInfo.java
  src/main/java/com/toongather/toongather/global/common/error/CommonRuntimeException.java
  src/main/java/com/toongather/toongather/global/security/jwt/JwtAuthenticationEntryPoint.java
Labels: feature, refactor

#25 [회원] 회원 controller 테스트 코드 작성 및 리팩토링
  src/main/java/com/toongather/toongather/domain/member/api/AuthApi.java
  src/main/java/com/toongather/toongather/domain/member/api/MemberApi.java
  src/main/java/com/toongather/toongather/domain/member/dto/MemberDTO.java
  src/main/java/com/toongather/toongather/domain/member/service/AuthService.java
  src/main/java/com/toongather/toongather/domain/member/service/MemberService.java
  src/main/java/com/toongather/toongather/global/common/advice/ApiExceptionAdvice.java
  src/main/java/com/toongather/toongather/global/common/error/CommonError.java
  src/main/java/com/toongather/toongather/global/config/SecurityConfig.java
  src/test/java/com/toongather/toongather/domain/member/api/MemberApiTest.java
Labels: refactor, test

#27 [웹툰] 기본 등록,수정,삭제 단위 테스트 추가
  build.gradle
  src/main/java/com/toongather/toongather/domain/webtoon/domain/WebtoonGenreKeyword.java
  src/main/java/com/toongather/toongather/domain/webtoon/dto/WebtoonRequest.java
  src/main/java/com/toongather/toongather/domain/webtoon/service/WebtoonService.java
  src/test/java/com/toongather/toongather/ToongatherApplicationTests.java
  src/test/java/com/toongather/toongather/domain/webtoon/api/WebtoonControllerTest.java
  src/test/java/com/toongather/toongather/domain/webtoon/domain/WebtoonTest.java
  src/test/java/com/toongather/toongather/domain/webtoon/repository/GenreKeywordRepositoryTest.java
  src/test/java/com/toongather/toongather/domain/webtoon/service/WebtoonServiceTest.java
Labels: test
